### ISSUE TITLE
Assignment 2

### ISSUE THREAD

**Issue by shraddhanair** [SrishtiGameLab/info-viz-s1c1-1617#3]
![hotlinedata2](https://cloud.githubusercontent.com/assets/20787338/17549224/e3c1c3b6-5f0c-11e6-999f-97c631c6dc04.jpg)
![lucydata2](https://cloud.githubusercontent.com/assets/20787338/17549225/e3f3e102-5f0c-11e6-99da-bb89325a6b61.jpg)

**Comment by yadurajiv** [comment]
Hi @shraddhanair could you post this as a reply to #2 rather than a new issue. Thanks
